/**
 * This code was generated by Builder.io.
 */
import React from "react";
import StarRating from "./StarRating";

export interface TestimonialCardProps {
  rating: number;
  quote: string;
  name: string;
  position: string;
  imageSrc: string;
  logoSrc: string;
}

const TestimonialCard: React.FC<TestimonialCardProps> = ({
  rating,
  quote,
  name,
  position,
  imageSrc,
  logoSrc,
}) => {
  return (
    <article className="flex overflow-hidden flex-col flex-1 shrink items-start basis-0 min-w-[240px]">
      <StarRating rating={rating} />
      <blockquote className="self-stretch mt-8 text-xl font-bold leading-snug text-black">
        "{quote}"
      </blockquote>
      <div className="flex flex-col items-start mt-8 text-base text-black">
        <img
          loading="lazy"
          src={imageSrc}
          alt={name}
          className="object-contain w-14 rounded-full aspect-square"
        />
        <div className="flex flex-col self-stretch mt-4">
          <p className="font-semibold">{name}</p>
          <p>{position}</p>
        </div>
        <img
          loading="lazy"
          src={logoSrc}
          alt="Company logo"
          className="object-contain mt-4 max-w-full aspect-[2.5] w-[120px]"
        />
      </div>
    </article>
  );
};

export default TestimonialCard;
