/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { ContactModal } from "../ui/contact-modal";

interface ActionButtonsProps {}

const ActionButtons: React.FC<ActionButtonsProps> = () => {
  return (
    <div className="flex gap-6 items-center mt-8 text-base text-black whitespace-nowrap">
      <ContactModal
        phoneNumber="393480463822"
        instagramUsername="angolodelleunghie_"
      />
    </div>
  );
};

export default ActionButtons;
