/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import ServiceCard from "./service-card";
import ActionButtons from "./action-buttons";
import { Brush, ShieldCheck } from "lucide-react";

interface CTASectionProps {}

const CTASection: React.FC<CTASectionProps> = () => {
  const services = [
    {
      icon: <ShieldCheck size={35} />,
      title: "Competenza Assicurata",
      description:
        "Scopri tecniche innovative per la cura delle unghie e tendenze all'avanguardia.",
    },
    {
      icon: <Brush size={35} />,
      title: "Servizi Personalizzati",
      description:
        "Ogni trattamento è personalizzato per soddisfare le tue esigenze uniche.",
    },
  ];

  return (
    <section className="w-full px-16 max-lg:px-5 py-28 max-lg:py-24">
      <div className="max-lg:w-full w-1/2 mx-auto">
        <Header />
        <div className="flex flex-wrap gap-6 items-start py-10 w-full max-lg:max-w-full">
          {services.map((service, index) => (
            <ServiceCard key={index} {...service} />
          ))}
        </div>
        <ActionButtons />
      </div>
    </section>
  );
};

export default CTASection;
