/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface HeaderProps {}

const Header: React.FC<HeaderProps> = () => {
  return (
    <header>
      <h4 className="font-semibold">Bellezza</h4>
      <article className="flex flex-col mt-4 w-full max-md:max-w-full">
        <h2 className="text-5xl font-bold leading-[58px] max-md:max-w-full max-md:text-4xl max-md:leading-[54px]">
          La tua esperta di unghie di fiducia
        </h2>
        <p className="mt-6 text-lg leading-7 max-md:max-w-full">
          Con anni di esperienza nel settore della bellezza, ti offro servizi di
          alta qualità. La mia passione per il lavoro si riflette in ogni
          trattamento.
        </p>
      </article>
    </header>
  );
};

export default Header;
