/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ServiceCardProps {
  icon: string;
  title: string;
  description: string;
}

const ServiceCard: React.FC<ServiceCardProps> = ({
  icon,
  title,
  description,
}) => {
  return (
    <article className="flex flex-col flex-1 shrink basis-0 min-w-[240px]">
      <img
        loading="lazy"
        src={icon}
        alt=""
        className="object-contain w-12 aspect-square"
      />
      <h3 className="mt-4 text-xl font-bold leading-snug">{title}</h3>
      <p className="mt-4 text-base leading-6">{description}</p>
    </article>
  );
};

export default ServiceCard;
