/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ServiceCardProps {
  icon: React.ReactNode;
  title: string;
  description: string;
}

const ServiceCard: React.FC<ServiceCardProps> = ({
  icon,
  title,
  description,
}) => {
  return (
    <article className="flex flex-col flex-1 shrink basis-0 min-w-[240px] my-10">
      <div className="flex flex-nowrap gap-2 items-center">
        {icon}
        <h3 className="text-xl font-bold leading-snug">{title}</h3>
      </div>

      <p className="mt-4 text-base leading-6">{description}</p>
    </article>
  );
};

export default ServiceCard;
